#!/bin/bash

echo -e "Enter a number"
read m
echo -e "Result: "

if ((m % 2 == 0 )); then
	echo "$m is Weird"
elif (( m % 2 != 0)) && ((m >= 2 )) && ((m <= 5 )); then
	echo "Not weird"
elif (( m % 2 != 0)) && ((m >= 6 )) && ((m >= 20 )); then
	echo "Weird"
elif (( m % 2 != 0 )) && ((m > 20 )); then
	echo "not weird"
fi
